# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 778647f43ad5ca92f8a5acbcb41cdf4840776db8de6f37f8a3491db207abfc17991a84a127789ddf6b4cc5782598000e0e716eec65434a8e192394b5919d6401

test:
  secret_key_base: 7af352e093867d496636c2b3521adfbbe02c824a635311b1b2b30adfecd01c77d334ee9b1fc9de064c53baa45ef109ae95a3315e38d07f23be1ce28e4e3686a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
